<?php

function migrate_books_menu() {
  $items = array();
  $items['migrate/books'] = array(
    'title' => t('Add new Islandora RDF relatationships to existing books'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migrate_books_confirmation_form'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('migrate all books'),
  );
  return $items;
}

function migrate_books_confirmation_form(&$form_state) {
  $description = 'This action cannot be undone. This utility module will add the fedora 
    relationships required by the current version of the Islandora Book Solution Pack.  
    The module is intended for <b>single use only</b>. If you are on a multisite it is safer 
    to update on a collection by collection basis. Select <i>Manage This Collection</i> from 
    within the collection you wish to update then select <i>Add new Islandora relationships to 
    book objects</i> to update all the books within that particular collection.';

  return confirm_form(
    $form, 
    'Are you sure you want to update ALL the books in the repository?', 
    'fedora/repository', 
    $description);
}

function migrate_books_confirmation_form_submit($form, &$form_state) {
  batch_process_book();
}

function migrate_books_islandora_collection_mangement($pid) {
  global $user;
  if (user_access('migrate books')) {
    module_load_include('inc', 'migrate_books', 'migrate_books_form');
    return drupal_get_form('migrate_books_form', $pid);
  }
}

function migrate_books_perm() {
  return array(
    'migrate books',
    'migrate all books'
  );
}

/**
 * Retreives all book pids within a collection
 * Each book is a added to a batch process to update the rels stream
 * @param PID $collection_pid
 */
function batch_process_book($collection_pid = null) {
  $condition = "";
  if ($collection_pid) {
    $condition = "and \$object <info:fedora/fedora-system:def/relations-external#isMemberOfCollection> <info:fedora/$collection_pid>";
  }
  $book_query = "select \$object from <#ri>
    where (\$object <fedora-model:hasModel> <info:fedora/islandora:bookCModel>
    or \$object <fedora-model:hasModel> <info:fedora/islandora:iaBookCModel>)
    $condition";
  $book_pids = process_book_query($book_query);
  $book_count = count($book_pids);

  $batch = array(
    'title' => "Processing $book_count book objects.",
    'operations' => array(),
    'init_message' => t('Preparing data...'),
    'progress_message' => t('@current of @total tasks completed.'),
  );

  foreach ($book_pids as $book_pid) {
    $batch['operations'][] = array('update_islandora_rdfstreams', array($book_pid));
    $page_num++;
  }
  batch_set($batch);
  batch_process("fedora/repository/$collection_pid");
}

function update_islandora_rdfstreams($book_pid) {
  $page_pids = islandora_update_book_rels_get_page_pids($book_pid);
  $count = 1;

  if (!empty($page_pids)) {
    foreach ($page_pids as $page_pid) {
      islandora_update_book_create_rels($book_pid, $page_pid, $count++);
    }
  }
}

function islandora_update_book_create_rels($book_pid, $pid, $page_number) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $rdf_string = <<<RDF
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<rdf:Description rdf:about="info:fedora/$pid">
	<hasModel xmlns="info:fedora/fedora-system:def/model#" rdf:resource="info:fedora/islandora:pageCModel"></hasModel>
	<isSequenceNumber xmlns="http://islandora.ca/ontology/relsext#">$page_number</isSequenceNumber>
	<isMemberOf xmlns="info:fedora/fedora-system:def/relations-external#" rdf:resource="info:fedora/$book_pid"></isMemberOf>
	<isSection xmlns="http://islandora.ca/ontology/relsext#">1</isSection>
	<isPageOf xmlns="http://islandora.ca/ontology/relsext#" rdf:resource="inf:fedora/$book_pid"></isPageOf>
  <isPageNumber xmlns="http://islandora.ca/ontology/relsext#">$page_number</isPageNumber>
</rdf:Description>
</rdf:RDF>
RDF;

  $item = new Fedora_Item($pid);
  $value = $item->modify_datastream_by_value($rdf_string, 'RELS-EXT', 'RELS-EXT', 'text/xml', $force = FALSE, $logMessage = 'Modified by Islandora', $quiet = FALSE);

  $item->forget();
}

function islandora_update_book_rels_get_page_pids($book_pid) {
  //return get_sorted_pages($book_pid); //not sure why we have two different functions
  $query = <<<XML
select \$object \$title from <#ri>
	where (\$object <dc:title> \$title
		and \$object <fedora-rels-ext:isMemberOf> <info:fedora/$book_pid>
		and \$object <fedora-model:state> <info:fedora/fedora-system:def/model#Active>)
	order by \$title
XML;


  module_load_include('inc', 'fedora_repository', 'CollectionClass');
  $collection = new CollectionClass($book_pid);
  $contents = $collection->getRelatedItems($book_pid, $query);
  $results_xml = simplexml_load_string($contents);
  $resultsarray = array();
  $book_pids = array();
  foreach ($results_xml->results->result as $result) {
    $page_pids[] = str_replace('info:fedora/', '', $result->object->attributes()->uri);
  }
  return $page_pids;
}

function process_book_query($query) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_utils');
  $query = htmlentities(urlencode($query));
  $content = '';

  $url = variable_get('fedora_repository_url', 'http://localhost:8080/fedora/risearch');
  $url .= "?type=tuples&flush=TRUE&format=csv&limit=$limit&offset=$offset&lang=itql&stream=on&query=" . $query;
  $content .= do_curl($url);
  $results = explode("\n", $content);
  return array_filter(preg_replace('/^info:fedora\/|"object"/', '', $results));
}
